version: '3.1'

networks:
  likvidatura:
    name: likvidatura

services:
  mysql_likvidatura:
    image: mysql:8.0.23
    container_name: mysql_likvidatura
    ports:
      - "3306:3306"
    networks:
      - likvidatura
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: likvidatura
    volumes:
      - mysqlDB:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  mysqlDB:
    driver: local
